### ISSUE TITLE
testing: fixes and improvements

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-angular-adapter#23]
While getting `laxar-mocks` ready for LaxarJS v2, a couple of issues arose with the AngularJS adapter.

 - [x] To support multiple LaxarJS `bootstrap` instances, we need to change the AngularJS boostrapping node from `document` to the LaxarJS `anchorElement`.

- [x] We do not need the additional `bootStrappingScope`. Instead, each boostrapping instance gets its own `$rootScope`.

- [x] The `reset` method should also clean up the custom `Promise`.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
